name = "jns-avatar-upload"
main = "src/index.ts"
compatibility_date = "2022-07-31"

node_compat = true

account_id = ""     
workers_dev = true  


# local
[vars]
BASE_WEB3_ENDPOINT = "https://rpc.testnet.jfinchain.com"
SUPPORTED_NETWORKS = ["harmony", "harmony-s1", "local", "localhost", "mainnet", "goerli", "ropsten","jfintestnet"]
REGISTRY_ADDRESS = "0x1FE51DdbA60F3Ec64DA002E5ccBc46e597049E24"
WRAPPER_ADDRESS = '{"jfintestnet": "0xc57de38dBcB35473773f84A553F2Ab5fC23B4653",  "mainnet": "", "goerli": "0x582224b8d4534F4749EFA4f22eF7241E0C56D4B8", "ropsten": "0xF82155e2a43Be0871821E9654Fc8Ae894FB8307C" }'
MULTICALL_ADDRESS = "0xcA11bde05977b3631167028862bE2a173976CA11"
BASE_REGISTRAR_ADDRESS = "0xb5caF25Cbb6760Ca6E815113e84108Fc1AC2ED41"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = 'jns'
preview_bucket_name = 'jns'
